### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by wolfsmensch** [coder-racer/Application-api-architecture#3]
Не уверен, на сколько актуально в этом проекте, но всеравно скажу.

Методы классов в идеально нужно комментировать по формату PHPDoc. Тогда IDE будут охотнее подхватывать описания методов и можно будет автоматически генерировать документацию по твоему коду.

Если это, конечно, нужно в вашем проекте.

**Comment by coder-racer** [comment]
fixed
